import React from 'react'
import '../styles/About.css';

function About() {
  return (
    <div className='about-container container'>
      <h1 className='about-h1'>About one world foundation</h1>
      <hr />

      <p>
      One world foundation, which was established in 1995 by Professor Kathrin Messner and Mr. Joseph Ortner and now proudly owns a 29-year-old-history which has been locally and internationally admired , is unique in its vision and composition among the other organizations operating in Sri Lanka. one world foundation has stepped on the Sri Lankan soil, especially in Ahungalla area, with the foresight of encouraging social mobility of people living in the area through creating educational opportunities that can be harnessed by the people free of charge and the umbrella nature of the organization has been capable of fueling this remarkable endeavor rendered since its establishment; that is, one world foundation is an umbrella organization that comprises of a guest house named Boganvillya, which is supposed to generate an income, and an educational unit named Free Education Unit, which is run by the income generated by its sister guest house and the monitory and material assistance of local and especially foreign philanthropists.
      </p>
      <p>
      The free education unit, which consists of several units such as Pre-school (Ahungalla and Katuwila), Language, ICT, Music, Sports, Women Cooperation, etc., is a special place in which a variety of educational and vocational programs are offered from a toddler to an adult free of charge. Around 1,100 students are now making the maximum use of these educational and vocational programs in order to achieve their goals under the guidance of around 44 teachers administered by a principal.
      </p>
      <p>
      one world foundation would like to reveal that it has decided to financially strengthen the free education unit with the intention of further improving the quality of the educational services offered and expanding the opportunities created for the people in the area in establishing a special unit called Vocational Training Unit, which is supposed to offer several demanding courses such as English, Tamil, ICT, Photography, etc. to anyone interested in the areas mentioned above on the weekend.
      </p>
      <p>
      one world foundation would also like to invite state and private sector employees and anyone interested in the courses offered to get qualified with the skills, which is the need of the hour in this global village, and knowledge offered through our courses which are scheduled to be lectured by a panel of qualified and experienced tutors and trainers while making a contribution towards humanity and achieving your career/personal goals.
      </p>
    </div>
  )
}

export default About